### DISCUSSION TITLE
I Must Be Missing A Step?

### DISCUSSION THREAD

**Discussion by 2ndLtAmazing** [neonwatty/meme-search#52] [Q&A] [answered]
Okay, so I'm probably going to sound like an idiot... but that is, at times, the cost of finding information.
I am having some difficulty identifying the steps to perform.

## On the upside, it does seem like this may be an appropriate opportunity to use memes to describe what's going on
![image](https://github.com/user-attachments/assets/7fe824e7-3d48-445a-b961-f91ba5837867)

So, somewhere between this:
>`docker compose -f docker-compose-pro.yml up`

and this:
>a meme exists in my database that I can search for

It would seem that I am missing something.

### The instructions for Pro say:
>### Installation instructions - pro version
>To start up the pro version of meme search pull this repository and start the server cluster with docker-compose

So I have a VM running a Debian Server with Docker that I'm managing with Portainer.
Then it says this:
>`docker compose -f docker-compose-pro.yml up`
>This pulls and starts containers for the app, database, and auto description generator. The app itself will run on port 3000 and is available at
>`http://localhost:3000`

So I have the portainer stack running with the docker compose file, and the docker images were pulled, and the containers are running and I can access what appears to be an empty database of memes at port 3000
![image](https://github.com/user-attachments/assets/9ba490fc-6f69-4a3b-bcc5-1f5a7eac203f)

### And then we're off to the races with:

>### Index your memes - pro version
>With the pro version you can index your memes by creating your own descriptions, or by generating descriptions automatically, as illustrated below.

### However, it kind of feels like this:
![image](https://github.com/user-attachments/assets/bfa88e7f-1003-4c04-9353-76ec4dc8fe37)

As far as I can tell, I just completed step 3, so I'm really close...  but don't see any way to have there be memes inside of my database, either by some means of putting them there, or via magical wish fulfillment.

Adding a directory just seems to tell me that I'm doing it wrong.
![image](https://github.com/user-attachments/assets/2b4a0810-1f46-4485-a412-9ba68a066862)

As I said, I'm sure I sound like an idiot, and I apologize for wasting anyone's time with this, I would be happy to RTFM, if there is somewhere else in TFM that I should R. If so, I just can't seem to find it.

### (On a side note, it took me a really long time to locate the memes that I used in this post.)

**Comment by neonwatty** [comment, marked as answer]
HA!  No problem!  The project is always improving - and that includes the setup instructions!

Here's my guess as to whats going on - but you confirm: did you mount your subdirectory of memes (e.g., `Test`) to your container running Meme Search?

Here's the relevant snippet from the [pro compose file](https://github.com/neonwatty/meme-search/blob/main/docker-compose-pro.yml)

```yaml
  meme_search_pro:
    image: ghcr.io/neonwatty/meme_search_pro:latest
    container_name: meme_search_pro
    environment:
      - DATABASE_URL=postgres://postgres:postgres@meme-search-db:5432/meme_search
    ports:
      - "3000:3000"
    depends_on:
      meme_search_db:
        condition: service_healthy
    volumes: # <-- any additional meme directory must be mounted here
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directories
 ```

Its that last line under `volumes` - thats the paydirt.   This part

```yaml
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directories
```

You need to add proper mounts to any additional subdirectory you'd like Meme Search to ingest.

So - for example - if you have a directory on your machine `/my/directory/of/memes/Test` you would need to mount it to the `meme_search_pro` service under `volumes` as

```yaml
      - /my/directory/of/memes/Test:/rails/public/memes/Test
```

Once this is done and the app is restarted you should be able to register your memes in the `Test` directory.

Hope this helps!  Let me know otherwise and we'll continue troubleshooting.

I'll also update the README with these instructions.  (edit: updated)
