### ISSUE TITLE
Configure RO mounts?

### ISSUE THREAD

**Issue by pypeaday** [neonwatty/meme-search#104]
This is a neat project - I've been using a dedicated immich server for my memes and it's working ok - I'd love to mount that directory to this container and compare but I don't want to give write access to the directory... I do'nt know the ins and outs of how this works but would it be possible to build in a way to index RO data volumes?

**Comment by neonwatty** [comment]
Can you try leveraging Docker's read-only spec for attached volumes - using the `ro` suffix?  I believe this should restrict actions to read-only in the associated containers.

For example, adjust the [pro compose file](https://github.com/neonwatty/meme-search/blob/main/docker-compose-pro.yml) mounts to the app and image-to-text generator like this.  Imagine you have a local directory of your personal memes at `/path-to-my/personal/memes`:

```yaml
version: "3.8"

services:
  meme_search_pro:
    .
    .
    volumes: # <-- any additional meme directory must be mounted here
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directories from repo
      - /path-to-my/personal/memes:/rails/public/my-personal-memes:ro  <---- note the "ro" suffix for read-only in the conrtainer

  image_to_text_generator:
    .
    .
    volumes: # <-- any additional meme directory must be mounted here
      - ./meme_search_pro/memes/:/app/public/memes # <-- example meme directories from repo
      - /path-to-my/personal/memes:/rails/public/my-personal-memes:ro  <---- note the "ro" suffix for read-only in the conrtainer
      - ./meme_search_pro/db_data/image_to_text_generator:/app/db
      - ./meme_search_pro/models:/root/.cache/huggingface

```

**Comment by pypeaday** [comment]
so I tried this:

```
services:
  meme_search:
    image: ghcr.io/neonwatty/meme-search:latest
    container_name: meme_search
    ports:
      - 8501:8501
    volumes:
      # - /tank/encrypted/docker/meme_search/data:/home/data
      - /tank/encrypted/docker/nextcloud-zfs/nextcloud/data/nic/files/Home/nic/MemesAndTweets/:/home/data:ro
```

I left the container alone overnight, logs looked like there was some tensorflow stuff happening, but this morning I can't search for anything

![Image](https://github.com/user-attachments/assets/f3ac0e79-f534-4982-b46a-cffe72e4f0f4)

I'll try with your example
