### ISSUE TITLE
Docker Compose env variable host/container conflicts

### ISSUE THREAD

**Issue by oderyn** [neonwatty/meme-search#111]
Should the DATABASE_URL use the ${DB_PORT:-5432} variable? Unless I am mistaken, the DB_PORT variable modifies the host access port in the meme_search_db, but the DATABASE_URL is setup for internal container access.

Also,"version" is deprecated in the latest versions of docker compose.

Here is an updated compose file.

```
services:
  meme_search_pro:
    build:
      context: ./meme_search_pro/meme_search_app
      dockerfile: Dockerfile
    container_name: meme_search_pro
    environment: # <-- you can adjust these values in your .env file
      DATABASE_URL: "postgres://postgres:postgres@meme-search-db:5432/meme_search"
      APP_HOST: "${APP_HOST:-localhost}"
      APP_PORT: "${APP_PORT:-3000}"
      GEN_PORT: "${GEN_PORT:-8000}"
      DOCKER_HOST_INTERNAL: "${DOCKER_HOST_INTERNAL:-host.docker.internal}"
    ports:
      - "${APP_PORT:-3000}:3000" # <--  adjust to desired local port for this service in your .env file
    depends_on:
      meme_search_db:
        condition: service_healthy
    volumes: # <-- any additional meme directory must be mounted here - and placed in the /rails/public/memes directory in the container (see example below)
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directory from the repository
      # -  /route/to/my/personal/additional_memes/:/rails/public/memes/additional_memes # <-- personal meme collection - must be placed inside /rails/public/memes in the container

  image_to_text_generator:
    build:
      context: ./meme_search_pro/image_to_text_generator
      dockerfile: Dockerfile
    container_name: image_to_text_generator
    environment: # <-- you can adjust these values in your .env file
      APP_HOST: "${APP_HOST:-localhost}"
      APP_PORT: "${APP_PORT:-3000}"
      GEN_PORT: "${GEN_PORT:-8000}"
      DOCKER_HOST_INTERNAL: "${DOCKER_HOST_INTERNAL:-host.docker.internal}"
    ports:
      - "${GEN_PORT:-8000}:8000" # <--  adjust to desired local port for this service in your .env file)"
    volumes: # <-- any additional meme directory must be mounted here - and placed in the /app/public/memes directory in the container (see example below)
      - ./meme_search_pro/memes/:/app/public/memes # <-- example meme directory from the repository
      # -  /route/to/my/personal/additional_memes/:/app/public/memes/additional_memes # <-- personal meme collection - must be placed inside /app/public/memes in the container
      - ./meme_search_pro/db_data/image_to_text_generator:/app/db
      - ./meme_search_pro/models:/root/.cache/huggingface
    deploy:
      resources:
        limits: # <-- roughly tested min memory for cpu usage
          memory: 12GB
        # reservations: # <-- uncomment for gpu usage
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]

  meme_search_db:
    image: pgvector/pgvector:pg17
    container_name: meme-search-db # note: must use - and not _ as ActiveRecord uses URI::RFC2396_Parser to parse database URLs
    volumes:
      - ./meme_search_pro/db_data/meme-search-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meme_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-5432}:5432" # <--  adjust to desired local port for this service in your .env file
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

```

And here is a sample .env file if anyone needs it:

```
# Database settings
DB_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=CHANGEME
POSTGRES_DB=meme_search
DATABASE_URL: "postgres://postgres:postgres@meme-search-db:5432/meme_search"

# Application settings
APP_HOST=0.0.0.0
APP_PORT=3000

# Generator service settings
GEN_PORT=8000

# Docker internal host
DOCKER_HOST_INTERNAL=host.docker.internal
```
