### ISSUE TITLE
Error On Fresh Deployment

### ISSUE THREAD

**Issue by 2ndLtAmazing** [neonwatty/meme-search#113]
Deploying this using Portainer, the meme_search_pro Container gives an error and exits with Code 1.

The container logs show this:

```
bin/rails aborted!
ActiveRecord::RecordNotFound: Couldn't find ImageCore with 'id'=1 (ActiveRecord::RecordNotFound)
/rails/db/seeds.rb:11:in `<main>'
Tasks: TOP => db:prepare
(See full trace by running task with --trace)
```

After changing nothing but deploying a 2nd time, the containers started without error.
(This same thing happened on multiple hosts, with the same log output)

After adding a directory and populating it with memes, and then updating the compose file with the new paths I was able to add the path inside of the application and the memes showed up.

However, whenever I click on "Generate Description" I get a "We're sorry, something went wrong" page.  And the logs show the following:

```
Failed to connect to local host at localhost:8000, failed with error: undefined method `name' for nil
Trying to connect to image_to_text_generator service directly
I, [2025-04-09T12:58:57.726467 #1]  INFO -- : [3d05f11b-79c2-47c1-a6fe-93e43f6c08a5] Completed 500 Internal Server Error in 223ms (ActiveRecord: 168.6ms (4 queries, 0 cached) | GC: 0.0ms)
E, [2025-04-09T12:58:57.731658 #1] ERROR -- : [3d05f11b-79c2-47c1-a6fe-93e43f6c08a5]   
[3d05f11b-79c2-47c1-a6fe-93e43f6c08a5] NoMethodError (undefined method `name' for nil):
[3d05f11b-79c2-47c1-a6fe-93e43f6c08a5] 
Causes:
[3d05f11b-79c2-47c1-a6fe-93e43f6c08a5] NoMethodError (undefined method `name' for nil)
[3d05f11b-79c2-47c1-a6fe-93e43f6c08a5]   
[3d05f11b-79c2-47c1-a6fe-93e43f6c08a5] app/controllers/image_cores_controller.rb:77:in `rescue in generate_description'
[3d05f11b-79c2-47c1-a6fe-93e43f6c08a5] app/controllers/image_cores_controller.rb:56:in `generate_description'

```

I'm running this on Docker installed on Debian12 and being managed with Portainer.

If I attempt to browse to the docker host using port 8000 I see this:
```
{"status":"HELLO WORLD"}
```
To prove that the port is pointing to the container, I got a "This site can’t be reached" when I tried again after stopping the image_to_text_generator container.
I've also verified that the Debian host is able to ping itself at "localhost".

This was the compose file used:

```
services:
  meme_search_pro:
    image: ghcr.io/neonwatty/meme_search_pro:latest
    container_name: meme_search_pro
    environment: # <-- you can adjust these values in your .env file
      DATABASE_URL: "postgres://postgres:postgres@meme-search-db:${DB_PORT:-5432}/meme_search"
      APP_HOST: "${APP_HOST:-localhost}"
      APP_PORT: "${APP_PORT:-3000}"
      GEN_PORT: "${GEN_PORT:-8000}"
      DOCKER_HOST_INTERNAL: "${DOCKER_HOST_INTERNAL:-host.docker.internal}"
    ports:
      - "${APP_PORT:-3000}:3000" # <--  adjust to desired local port for this service in your .env file
    depends_on:
      meme_search_db:
        condition: service_healthy
    volumes: # <-- any additional meme directory must be mounted here - and placed in the /rails/public/memes directory in the container (see example below)
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directory from the repository
      -  /mnt/memes/primary/:/rails/public/memes/primary # <-- personal meme collection - must be placed inside /rails/public/memes in the container
      # -  /route/to/my/personal/additional_memes/:/rails/public/memes/additional_memes # <-- personal meme collection - must be placed inside /rails/public/memes in the container


  image_to_text_generator:
    image: ghcr.io/neonwatty/image_to_text_generator:latest
    container_name: image_to_text_generator
    environment: # <-- you can adjust these values in your .env file
      APP_HOST: "${APP_HOST:-localhost}"
      APP_PORT: "${APP_PORT:-3000}"
      GEN_PORT: "${GEN_PORT:-8000}"
      DOCKER_HOST_INTERNAL: "${DOCKER_HOST_INTERNAL:-host.docker.internal}"
    ports:
      - "${GEN_PORT:-8000}:8000" # <--  adjust to desired local port for this service in your .env file)"
    volumes: # <-- any additional meme directory must be mounted here - and placed in the /app/public/memes directory in the container (see example below)
      - ./meme_search_pro/memes/:/app/public/memes # <-- example meme directory from the repository
      -  /mnt/memes/primary/:/app/public/memes/primary # <-- personal meme collection - must be placed inside /app/public/memes in the container
      # -  /route/to/my/personal/additional_memes/:/app/public/memes/additional_memes # <-- personal meme collection - must be placed inside /app/public/memes in the container
      - ./meme_search_pro/db_data/image_to_text_generator:/app/db
      - ./meme_search_pro/models:/root/.cache/huggingface
    deploy:
      resources:
        limits: # <-- roughly tested min memory for cpu usage
          memory: 12GB
        # reservations: # <-- uncomment for gpu usage
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]

  meme_search_db:
    image: pgvector/pgvector:pg17
    container_name: meme-search-db # note: must use - and not _ as ActiveRecord uses URI::RFC2396_Parser to parse database URLs
    volumes:
      - ./meme_search_pro/db_data/meme-search-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meme_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT:-5432}:5432" # <--  adjust to desired local port for this service in your .env file
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
```
